const coordenadasData = {
  tandil: {
    nombre: "Tandil",
    provincia: "Prov. de Buenos Aires",
    zona: true,
    latitud: -37.3217,
    longitud: -59.1332,
  },
  "mar-del-plata-mdq": {
    nombre: "Mar del Plata (MDQ)",
    provincia: "Prov. de Buenos Aires",
    zona: true,
    latitud: -38.0055,
    longitud: -57.5426,
  },
  "la-plata": {
    nombre: "La Plata",
    provincia: "Prov. de Buenos Aires",
    zona: true,
    latitud: -34.9205,
    longitud: -57.9536,
  },
  "san-vicente": {
    nombre: "San Vicente",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -35.0229,
    longitud: -58.4206,
  },
  quilmes: {
    nombre: "Quilmes",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.729,
    longitud: -58.2676,
  },
  "presidente-peron": {
    nombre: "Presidente Peron",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.9617,
    longitud: -58.3355,
  },
  "lomas-de-zamora": {
    nombre: "Lomas de Zamora",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.7609,
    longitud: -58.4036,
  },
  lanus: {
    nombre: "Lanús",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.7065,
    longitud: -58.3875,
  },
  "florencio-varela": {
    nombre: "Florencio Varela",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.8286,
    longitud: -58.2702,
  },
  ezeiza: {
    nombre: "Ezeiza",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.8211,
    longitud: -58.5202,
  },
  "esteban-echeverria": {
    nombre: "Esteban Echeverría",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.8599,
    longitud: -58.5142,
  },
  berazategui: {
    nombre: "Berazategui",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.7634,
    longitud: -58.2117,
  },
  avellaneda: {
    nombre: "Avellaneda",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.6619,
    longitud: -58.3636,
  },
  "almirante-brown": {
    nombre: "Almirante Brown",
    provincia: "GBA Zona Sur",
    zona: true,
    latitud: -34.8053,
    longitud: -58.3147,
  },
  "tres-de-febrero": {
    nombre: "Tres de Febrero",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.5965,
    longitud: -58.566,
  },
  "san-miguel": {
    nombre: "San Miguel",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.5415,
    longitud: -58.7132,
  },
  moron: {
    nombre: "Morón",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.6534,
    longitud: -58.6194,
  },
  moreno: {
    nombre: "Moreno",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.6558,
    longitud: -58.7918,
  },
  merlo: {
    nombre: "Merlo",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.6604,
    longitud: -58.7292,
  },
  "la-matanza": {
    nombre: "La Matanza",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.7618,
    longitud: -58.5479,
  },
  ituzaingo: {
    nombre: "Ituzaingó",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.6553,
    longitud: -58.6715,
  },
  hurlingham: {
    nombre: "Hurlingham",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.589,
    longitud: -58.6359,
  },
  "general-rodriguez": {
    nombre: "General Rodriguez",
    provincia: "GBA Zona Oeste",
    zona: true,
    latitud: -34.6124,
    longitud: -58.9472,
  },
  "vicente-lopez": {
    nombre: "Vicente López",
    provincia: "GBA Zona Norte",
    zona: true,
    latitud: -34.5213,
    longitud: -58.5029,
  },
  "tigre-nordelta": {
    nombre: "Tigre - Nordelta",
    provincia: "GBA Zona Norte",
    zona: true,
    latitud: -34.4262,
    longitud: -58.5796,
  },
  "san-isidro": {
    nombre: "San Isidro",
    provincia: "GBA Zona Norte",
    zona: true,
    latitud: -34.4744,
    longitud: -58.5237,
  },
  "san-fernando": {
    nombre: "San Fernando",
    provincia: "GBA Zona Norte",
    zona: true,
    latitud: -34.443,
    longitud: -58.5629,
  },
  pilar: {
    nombre: "Pilar",
    provincia: "GBA Zona Norte",
    zona: true,
    latitud: -34.4596,
    longitud: -58.9088,
  },
  "general-san-martin": {
    nombre: "General San Martin",
    provincia: "GBA Zona Norte",
    zona: true,
    latitud: -34.5703,
    longitud: -58.555,
  },
  escobar: {
    nombre: "Escobar",
    provincia: "GBA Zona Norte",
    zona: true,
    latitud: -34.3416,
    longitud: -58.7848,
  },
  "villa-urquiza": {
    nombre: "Villa Urquiza",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5737,
    longitud: -58.4874,
  },
  "villa-soldati": {
    nombre: "Villa Soldati",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6671,
    longitud: -58.4523,
  },
  "villa-santa-rita": {
    nombre: "Villa Santa Rita",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6187,
    longitud: -58.4813,
  },
  "villa-riachuelo": {
    nombre: "Villa Riachuelo",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6719,
    longitud: -58.4492,
  },
  "villa-real": {
    nombre: "Villa Real",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6254,
    longitud: -58.5175,
  },
  "villa-pueyrredon": {
    nombre: "Villa Pueyrredón",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5734,
    longitud: -58.5033,
  },
  "villa-ortuzar": {
    nombre: "Villa Ortúzar",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5799,
    longitud: -58.4717,
  },
  "villa-luro": {
    nombre: "Villa Luro",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6369,
    longitud: -58.4973,
  },
  "villa-lugano": {
    nombre: "Villa Lugano",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6782,
    longitud: -58.4756,
  },
  "villa-general-mitre": {
    nombre: "Villa General Mitre",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6027,
    longitud: -58.4753,
  },
  "villa-devoto": {
    nombre: "Villa Devoto",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6009,
    longitud: -58.5144,
  },
  "villa-del-parque": {
    nombre: "Villa del Parque",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.597,
    longitud: -58.4936,
  },
  "villa-crespo": {
    nombre: "Villa Crespo",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5981,
    longitud: -58.4489,
  },
  versalles: {
    nombre: "Versalles",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6252,
    longitud: -58.5112,
  },
  "velez-sarsfield": {
    nombre: "Vélez Sarsfield",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6308,
    longitud: -58.4972,
  },
  "san-telmo": {
    nombre: "San Telmo",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6212,
    longitud: -58.3731,
  },
  "san-nicolas": {
    nombre: "San Nicolas",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6047,
    longitud: -58.3878,
  },
  "san-cristobal": {
    nombre: "San Cristobal",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.624,
    longitud: -58.4039,
  },
  saavedra: {
    nombre: "Saavedra",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5542,
    longitud: -58.4882,
  },
  retiro: {
    nombre: "Retiro",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5911,
    longitud: -58.3745,
  },
  "recoleta-barrio-norte": {
    nombre: "Recoleta - Barrio Norte",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5895,
    longitud: -58.3974,
  },
  "puerto-madero": {
    nombre: "Puerto Madero",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6107,
    longitud: -58.3621,
  },
  "parque-patricios": {
    nombre: "Parque Patricios",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6355,
    longitud: -58.3988,
  },
  "parque-chas": {
    nombre: "Parque Chas",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5794,
    longitud: -58.4644,
  },
  "parque-chacabuco": {
    nombre: "Parque Chacabuco",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6342,
    longitud: -58.4322,
  },
  "parque-avellaneda": {
    nombre: "Parque Avellaneda",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.647,
    longitud: -58.4761,
  },
  palermo: {
    nombre: "Palermo",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5885,
    longitud: -58.4297,
  },
  nunez: {
    nombre: "Núñez",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5428,
    longitud: -58.4664,
  },
  "nueva-pompeya": {
    nombre: "Nueva Pompeya",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.647,
    longitud: -58.4215,
  },
  "monte-castro": {
    nombre: "Monte Castro",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6204,
    longitud: -58.5096,
  },
  monserrat: {
    nombre: "Monserrat",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6118,
    longitud: -58.3816,
  },
  mataderos: {
    nombre: "Mataderos",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6572,
    longitud: -58.5048,
  },
  liniers: {
    nombre: "Liniers",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6431,
    longitud: -58.5175,
  },
  "la-paternal": {
    nombre: "La Paternal",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5968,
    longitud: -58.464,
  },
  "la-boca": {
    nombre: "La Boca",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6345,
    longitud: -58.3631,
  },
  floresta: {
    nombre: "Floresta",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6287,
    longitud: -58.4726,
  },
  flores: {
    nombre: "Flores",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6353,
    longitud: -58.4618,
  },
  constitucion: {
    nombre: "Constitución",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6243,
    longitud: -58.3843,
  },
  "congreso-tribunales": {
    nombre: "Congreso - Tribunales",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6098,
    longitud: -58.3929,
  },
  colegiales: {
    nombre: "Colegiales",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5735,
    longitud: -58.4549,
  },
  coghlan: {
    nombre: "Coghlan",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.567,
    longitud: -58.4781,
  },
  chacarita: {
    nombre: "Chacarita",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5889,
    longitud: -58.4529,
  },
  caballito: {
    nombre: "Caballito",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6182,
    longitud: -58.4424,
  },
  boedo: {
    nombre: "Boedo",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6307,
    longitud: -58.4208,
  },
  belgrano: {
    nombre: "Belgrano",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5614,
    longitud: -58.4565,
  },
  barracas: {
    nombre: "Barracas",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6464,
    longitud: -58.3806,
  },
  "balvanera-once": {
    nombre: "Balvanera (Once)",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6091,
    longitud: -58.403,
  },
  almagro: {
    nombre: "Almagro",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6111,
    longitud: -58.4204,
  },
  agronomia: {
    nombre: "Agronomía",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.5949,
    longitud: -58.4837,
  },
  abasto: {
    nombre: "Abasto",
    provincia: "Capital Federal (CABA)",
    zona: true,
    latitud: -34.6042,
    longitud: -58.4101,
  },
};
