HOMBRE = 1
MUJER = 2

GENDER_CHOICES = (
    (HOMBRE, "HOMBRE"),
    (MUJER, "MUJER"),
)

# model: UserAttachment

USER_IMAGE = 1
USER_DNI = 2
USER_MATRICULA = 3

SOURCE_CONTENT_TYPE_CHOICES = (
    (USER_IMAGE, "USER_IMAGE"),
    (USER_DNI, "USER_DNI"),
    (USER_MATRICULA, "USER_MATRICULA"),
)
