# Generated by Django 4.2.7 on 2024-03-02 18:19

import apps.psychology.models.management_membership_plan
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.upload_files


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminEmailNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("object_id", models.IntegerField(db_index=True)),
                (
                    "content_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "PAGO_DEL_USUARIO"),
                            (2, "MENSAJE_AL_PROFESIONAL"),
                        ],
                        db_index=True,
                    ),
                ),
                ("admin_email", models.EmailField(max_length=254)),
                ("was_reported", models.BooleanField(db_index=True, default=False)),
                ("seen_notification", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Notificación de Email",
                "verbose_name_plural": "Notificaciones de Email",
            },
        ),
        migrations.CreateModel(
            name="Carreer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Carrera",
                "verbose_name_plural": "Carreras",
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("flag_icon", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Idioma",
                "verbose_name_plural": "Idiomas",
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("alias", models.CharField(max_length=255)),
                (
                    "membership_plan",
                    models.SmallIntegerField(
                        choices=[
                            (1, "BASIC_PLAN"),
                            (2, "PREMIUM_PLAN"),
                            (3, "VIP_PLAN"),
                        ],
                        db_index=True,
                        default=1,
                        help_text="Membership plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Planes",
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Especialización",
                "verbose_name_plural": "Especializaciones",
            },
        ),
        migrations.CreateModel(
            name="UserSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "specialization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_specialization_set",
                        to="psychology.specialization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_specialization_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Especialización del usuario ",
                "verbose_name_plural": "Especializaciones de los usuarios",
            },
        ),
        migrations.CreateModel(
            name="UserPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "type",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(1, "MONTHLY_PAYMENT"), (2, "ANNUAL_PAYMENT")],
                        db_index=True,
                        default=1,
                        null=True,
                    ),
                ),
                (
                    "membership_plan",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "BASIC_PLAN"),
                            (2, "PREMIUM_PLAN"),
                            (3, "VIP_PLAN"),
                        ],
                        db_index=True,
                        default=1,
                        help_text="Membership plan",
                        null=True,
                    ),
                ),
                ("was_paid", models.BooleanField(db_index=True, default=False)),
                ("was_reported", models.BooleanField(db_index=True, default=False)),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_payment_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago del usuario",
                "verbose_name_plural": "Pagos de los usuarios",
            },
        ),
        migrations.CreateModel(
            name="UserLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_language_set",
                        to="psychology.language",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_language_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Idioma de usuario",
                "verbose_name_plural": "Idiomas de los usuarios",
            },
        ),
        migrations.CreateModel(
            name="UserCarreer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "service_method",
                    models.SmallIntegerField(
                        choices=[
                            (1, "PRESENCIAL"),
                            (2, "VIRTUAL"),
                            (3, "PRESENCIAL/VIRTUAL"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "service_modality",
                    models.SmallIntegerField(
                        choices=[(1, "INDIVIDUAL"), (2, "GRUPAL")], default=1
                    ),
                ),
                ("experience_summary", models.TextField(blank=True, null=True)),
                (
                    "carreer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_carreer_set",
                        to="psychology.carreer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_carreer_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesión del usuario",
                "verbose_name_plural": "Profesión de los usuarios",
            },
        ),
        migrations.CreateModel(
            name="UserAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=utils.upload_files.upload_attachment_file,
                    ),
                ),
                (
                    "media_file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        null=True,
                        upload_to=utils.upload_files.upload_attachment_file,
                    ),
                ),
                (
                    "source_content_type",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "USER_IMAGE"),
                            (2, "USER_DNI"),
                            (3, "USER_MATRICULA"),
                        ],
                        db_index=True,
                        null=True,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("size", models.IntegerField(blank=True, null=True)),
                ("url_path", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_attachment_created_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_attachment_updated_by_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo del usuario",
                "verbose_name_plural": "Archivos de los usuarios",
            },
        ),
        migrations.CreateModel(
            name="MembershipPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("price", models.FloatField(default=0)),
                ("promotional_price", models.FloatField(default=0)),
                (
                    "membership_options",
                    models.JSONField(
                        blank=True,
                        default=apps.psychology.models.management_membership_plan.default_membership_options,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_price_created_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_price_edited_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="psychology.membership",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio del plan",
                "verbose_name_plural": "Precios por planes",
            },
        ),
        migrations.CreateModel(
            name="HistoryMembershipPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("price", models.FloatField(default=0)),
                (
                    "membership_price",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="history_membership_price_set",
                        to="psychology.membershipprice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ContactMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "full_name",
                    models.CharField(help_text="Visitor[external]", max_length=50),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True, max_length=50, verbose_name="email address"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True
                    ),
                ),
                ("message", models.TextField()),
                ("was_reported", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Professional",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="professional_contact_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Professional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Derivaciôn",
                "verbose_name_plural": "Derivaciones",
            },
        ),
        migrations.AddConstraint(
            model_name="adminemailnotification",
            constraint=models.UniqueConstraint(
                fields=("object_id", "content_type"),
                name="unique notification for admin",
            ),
        ),
        migrations.AddConstraint(
            model_name="userspecialization",
            constraint=models.UniqueConstraint(
                fields=("user", "specialization"), name="unique specialization for user"
            ),
        ),
        migrations.AddConstraint(
            model_name="userlanguage",
            constraint=models.UniqueConstraint(
                fields=("user", "language"), name="unique language for user"
            ),
        ),
        migrations.AddConstraint(
            model_name="usercarreer",
            constraint=models.UniqueConstraint(
                fields=("user", "carreer"), name="unique carreer for user"
            ),
        ),
    ]
